export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
//AUTH
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS";
export const GET_PROFILES_FAIL = "GET_PROFILES_FAIL";
export const GET_PR_SUCCESS = "GET_PR_SUCCESS";
export const GET_PR_FAIL = "GET_PR_FAIL";

export const EXP_TO_STORE="EXP_TO_STORE"
export const ED_TO_STORE="ED_TO_STORE"
export const CLEAR_TMP_STORE="CLEAR_TMP_STORE"
export const SOCIAL_TO_STORE="SOCIAL_TO_STORE"
export const PROFILE_TO_DB_SUCCESS="PROFILE_TO_DB_SUCCESS"
export const PROFILE_TO_DB_FAIL="PROFILE_TO_DB_FAIL"

export const FETCH_POSTS_LOADED = "FETCH_POSTS_LOADED";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";
//SINGLE POST
export const FETCH_SINGLE_POST_LOADED = "FETCH_SINGLE_POST_LOADED";
export const FETCH_SINGLE_POST_SUCCESS = "FETCH_SINGLE_POST_SUCCESS";
export const FETCH_SINGLE_POST_ERROR = "FETCH_SINGLE_POST_ERROR";

export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT = "GET_PROJECT";
export const PROJECT_ERROR = "PROJECT_ERROR";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
