export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";


export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";


export const  GET_PROFILES_SUCCESS='GET_PROFILES_SUCCESS'
export const  GET_PROFILES_FAIL='GET_PROFILES_FAIL'
export const GET_PR_SUCCESS = "GET_PR_SUCCESS";
export const GET_PR_FAIL = "GET_PR_FAIL";

